# Generated by Django 4.2.9 on 2024-04-30 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "question_type",
                    models.CharField(choices=[("RK", "Ranking")], max_length=2),
                ),
                ("question_text", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="play.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TriviaGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("played", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RankingQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="play.question",
                    ),
                ),
            ],
            bases=("play.question",),
        ),
        migrations.AddField(
            model_name="question",
            name="trivia_game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="play.triviagame",
            ),
        ),
        migrations.CreateModel(
            name="RankingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.CharField(max_length=255)),
                ("points", models.PositiveIntegerField(default=1)),
                ("correct_rank", models.PositiveIntegerField()),
                ("value_text", models.CharField(blank=True, max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="play.rankingquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["correct_rank"],
                "unique_together": {("question", "correct_rank")},
            },
        ),
    ]
