# Generated by Django 4.2.9 on 2024-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="id",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
