# Generated by Django 4.2.9 on 2024-07-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0002_remove_category_id_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(choices=[("RK", "Ranking")], max_length=30),
        ),
    ]
