# Generated by Django 4.2.9 on 2024-11-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_remove_question_image_question_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="image",
        ),
        migrations.AddField(
            model_name="answer",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
