# Generated by Django 4.2.9 on 2024-12-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_remove_category_game_category_games"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="game_phase",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
