# Generated by Django 4.2.17 on 2025-01-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_remove_answer_answers_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="answer_url",
            new_name="answer_image_url",
        ),
    ]
