# Generated by Django 4.2.17 on 2025-01-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0012_rename_answer_url_answer_answer_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
