# Generated by Django 4.2.17 on 2025-01-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0013_question_answer_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="image_url",
            new_name="question_image_url",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="image_url",
            new_name="question_image_url",
        ),
    ]
