# Generated by Django 4.2.17 on 2025-01-09 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0018_questionround_round_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionround",
            options={"ordering": ["round_number"]},
        ),
    ]
