# Generated by Django 4.2.17 on 2025-01-11 18:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0019_alter_questionround_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="description",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
