# Generated by Django 4.2.17 on 2025-01-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0020_alter_game_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_password_protected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
