# Generated by Django 4.2.18 on 2025-02-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0022_remove_answer_is_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_order",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
