# Generated by Django 4.2.9 on 2024-11-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_remove_answer_rank_answer_answer_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="image",
        ),
        migrations.AddField(
            model_name="question",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
