# Generated by Django 4.2.9 on 2024-11-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_remove_question_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="game",
        ),
        migrations.AddField(
            model_name="category",
            name="games",
            field=models.ManyToManyField(related_name="categories", to="quiz.game"),
        ),
    ]
