# Generated by Django 4.2.9 on 2024-12-07 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_question_game_phase"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="question",
            name="game_phase",
        ),
        migrations.AddField(
            model_name="question",
            name="game_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.questionround",
            ),
        ),
    ]
