# Generated by Django 4.2.17 on 2025-01-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_questionround_remove_question_game_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="answer_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="answers_img",
            field=models.URLField(blank=True, null=True),
        ),
    ]
