# Generated by Django 4.2.17 on 2025-01-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0014_rename_image_url_answer_question_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="games",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="quiz.game"
            ),
        ),
    ]
