# Generated by Django 4.2.17 on 2025-01-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0016_alter_question_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_bank",
            field=models.TextField(blank=True, null=True),
        ),
    ]
