# Generated by Django 4.2.17 on 2025-02-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0021_game_is_password_protected_game_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="is_correct",
        ),
    ]
