# Generated by Django 4.2.18 on 2025-02-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0023_game_game_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player", models.CharField(max_length=100)),
                ("avg_final_place", models.FloatField()),
                ("total_wins", models.IntegerField()),
                ("avg_zscore_total_points", models.FloatField()),
                ("avg_total_points", models.FloatField()),
                ("avg_pct_total_points", models.FloatField()),
                ("avg_normalized_total_points", models.FloatField()),
                ("avg_pct_rd1_points", models.FloatField()),
                ("avg_pct_rd2_points", models.FloatField()),
                ("avg_pct_final_rd_points", models.FloatField()),
                ("games_played", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_date", models.DateField()),
                ("players", models.CharField(max_length=300)),
                ("place", models.IntegerField()),
                ("winner", models.BooleanField()),
                ("Round_1", models.IntegerField()),
                ("Round_2", models.IntegerField()),
                ("Final", models.IntegerField()),
                ("Total", models.IntegerField()),
                ("pct_rd1", models.FloatField()),
                ("pct_rd2", models.FloatField()),
                ("pct_final", models.FloatField()),
                ("pct_total", models.FloatField()),
                ("normalized_total", models.FloatField()),
                ("zscore_total", models.FloatField()),
            ],
            options={
                "unique_together": {("game_date", "players")},
            },
        ),
    ]
