# Generated by Django 4.2.18 on 2025-03-29 06:23

from django.db import migrations
import quiz.fields


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0025_contentupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_image_url",
            field=quiz.fields.CloudFrontURLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question_image_url",
            field=quiz.fields.CloudFrontURLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_image_url",
            field=quiz.fields.CloudFrontURLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_image_url",
            field=quiz.fields.CloudFrontURLField(blank=True, max_length=255, null=True),
        ),
    ]
