# Generated by Django 4.2.18 on 2025-04-11 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0028_alter_answer_answer_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["display_order", "id"]},
        ),
    ]
