# Generated by Django 4.2.18 on 2025-05-06 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0029_alter_answer_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="explanation",
        ),
    ]
