# Generated by Django 4.2.18 on 2025-05-26 21:13

from django.db import migrations
import quiz.fields
import quiz.storage


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0030_remove_answer_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="answer_video",
            field=quiz.fields.S3VideoField(
                blank=True,
                null=True,
                storage=quiz.storage.S3MediaStorage(),
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="answer_video_url",
            field=quiz.fields.CloudFrontURLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="question_video",
            field=quiz.fields.S3VideoField(
                blank=True,
                null=True,
                storage=quiz.storage.S3MediaStorage(),
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question_video_url",
            field=quiz.fields.CloudFrontURLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_video",
            field=quiz.fields.S3VideoField(
                blank=True,
                null=True,
                storage=quiz.storage.S3MediaStorage(),
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_video_url",
            field=quiz.fields.CloudFrontURLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="question_video",
            field=quiz.fields.S3VideoField(
                blank=True,
                null=True,
                storage=quiz.storage.S3MediaStorage(),
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_video_url",
            field=quiz.fields.CloudFrontURLField(blank=True, max_length=255, null=True),
        ),
    ]
