# Generated by Django 4.2.18 on 2025-12-30 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0033_gamesession_max_teams"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sessionteam",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sessionteam",
            name="session",
        ),
        migrations.AlterUniqueTogether(
            name="teamanswer",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="teamanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="teamanswer",
            name="team",
        ),
        migrations.DeleteModel(
            name="GameSession",
        ),
        migrations.DeleteModel(
            name="SessionTeam",
        ),
        migrations.DeleteModel(
            name="TeamAnswer",
        ),
    ]
