# Generated by Django 4.2.18 on 2025-12-30 23:46

from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0034_alter_sessionteam_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=6, unique=True)),
                ("admin_name", models.CharField(max_length=100)),
                (
                    "admin_token",
                    models.CharField(
                        default=secrets.token_urlsafe, max_length=64, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lobby", "Waiting for Teams"),
                            ("playing", "Game in Progress"),
                            ("paused", "Paused (Admin Disconnected)"),
                            ("scoring", "Scoring Round"),
                            ("completed", "Game Completed"),
                        ],
                        default="lobby",
                        max_length=20,
                    ),
                ),
                (
                    "status_before_pause",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("max_teams", models.PositiveIntegerField(default=16)),
                ("allow_late_joins", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_last_seen", models.DateTimeField(auto_now_add=True)),
                (
                    "current_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="quiz.question",
                    ),
                ),
                (
                    "current_round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="quiz.questionround",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="quiz.game",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Not Started"),
                            ("active", "In Progress"),
                            ("locked", "Answers Locked"),
                            ("scored", "Scoring Complete"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("scored_at", models.DateTimeField(blank=True, null=True)),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.questionround",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_rounds",
                        to="quiz.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["round__round_number"],
                "unique_together": {("session", "round")},
            },
        ),
        migrations.CreateModel(
            name="SessionTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe, max_length=64, unique=True
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("joined_late", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="quiz.gamesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "joined_at"],
                "unique_together": {("session", "name")},
            },
        ),
        migrations.CreateModel(
            name="TeamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True, default="")),
                ("is_locked", models.BooleanField(default=False)),
                ("points_awarded", models.IntegerField(blank=True, null=True)),
                ("scored_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
                (
                    "session_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.sessionround",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.sessionteam",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session_round", "team"],
                        name="quiz_teaman_session_4b4dea_idx",
                    )
                ],
                "unique_together": {("team", "question")},
            },
        ),
    ]
