# Generated by Django 4.2.18 on 2026-01-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0035_gamesession_sessionround_sessionteam_teamanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="allow_team_navigation",
            field=models.BooleanField(
                default=False,
                help_text="Allow teams to navigate between questions in a round",
            ),
        ),
    ]
