# Generated by Django 4.2.18 on 2026-01-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0037_add_reviewing_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teamanswer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="teamanswer",
            name="answer_part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_answers",
                to="quiz.answer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teamanswer",
            unique_together={("team", "question", "answer_part")},
        ),
        migrations.AddIndex(
            model_name="teamanswer",
            index=models.Index(
                fields=["team", "question"], name="quiz_teaman_team_id_141287_idx"
            ),
        ),
    ]
