# Generated by Django 4.2.18 on 2026-01-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0038_add_answer_part_to_teamanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("lobby", "Waiting for Teams"),
                    ("playing", "Game in Progress"),
                    ("paused", "Paused (Admin Disconnected)"),
                    ("scoring", "Scoring Round"),
                    ("reviewing", "Reviewing Answers"),
                    ("leaderboard", "Showing Leaderboard"),
                    ("completed", "Game Completed"),
                ],
                default="lobby",
                max_length=20,
            ),
        ),
    ]
