# Generated by Django 4.2.18 on 2026-02-18 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0039_add_leaderboard_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Public games can be hosted by any authenticated user",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created/owns this game",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_games",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="host_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created/hosts this session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hosted_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_game_admin",
                    models.BooleanField(
                        default=False, help_text="Can create and edit games"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
