# Generated by Django 4.2.18 on 2026-02-18 02:06

from django.db import migrations


def assign_games_to_admin(apps, schema_editor):
    """Assign all existing games to the first superuser and create UserProfiles."""
    User = apps.get_model("auth", "User")
    Game = apps.get_model("quiz", "Game")
    UserProfile = apps.get_model("quiz", "UserProfile")

    # Get the first superuser
    superuser = User.objects.filter(is_superuser=True).first()

    if superuser:
        # Assign all games without an owner to the superuser
        Game.objects.filter(owner__isnull=True).update(owner=superuser)

        # Create UserProfile for the superuser with is_game_admin=True
        UserProfile.objects.get_or_create(
            user=superuser, defaults={"is_game_admin": True}
        )

    # Create UserProfile for all users who don't have one
    for user in User.objects.all():
        UserProfile.objects.get_or_create(
            user=user, defaults={"is_game_admin": user.is_superuser}
        )


def reverse_assign_games(apps, schema_editor):
    """Reverse: Remove owner from all games (cannot restore original state)."""
    Game = apps.get_model("quiz", "Game")
    Game.objects.all().update(owner=None)


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0040_game_is_public_game_owner_gamesession_host_user_and_more"),
    ]

    operations = [
        migrations.RunPython(assign_games_to_admin, reverse_assign_games),
    ]
