# Generated by Django 5.2.13 on 2026-04-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0042_add_is_example_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
