# Generated by Django 5.2.13 on 2026-04-24 02:27

from django.db import migrations
from django.contrib.auth.hashers import make_password


def hash_existing_passwords(apps, schema_editor):
    """Hash any existing plain-text game passwords."""
    Game = apps.get_model("quiz", "Game")
    for game in Game.objects.filter(password__isnull=False).exclude(password=""):
        # Skip if already hashed (Django password hashes have specific prefixes)
        if game.password and not game.password.startswith(
            ("pbkdf2_sha256$", "argon2", "bcrypt")
        ):
            game.password = make_password(game.password)
            game.save(update_fields=["password"])


def reverse_hash_passwords(apps, schema_editor):
    """Cannot reverse password hashing - this is a one-way operation."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0043_extend_password_field"),
    ]

    operations = [
        migrations.RunPython(hash_existing_passwords, reverse_hash_passwords),
    ]
