# Generated by Django 5.2.13 on 2026-05-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0046_fix_site_and_usernames"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["game", "question_number"]},
        ),
    ]
