# Generated by Django 5.2.13 on 2026-06-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0047_alter_game_options_alter_question_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Auto-assigned sequential number (null for drafts)",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="has_been_played",
            field=models.BooleanField(
                default=False, help_text="Whether this game has ever been hosted/played"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="is_draft",
            field=models.BooleanField(
                default=False,
                help_text="Draft games are not published and do not appear in game lists",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="legacy_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Original Month-Year name for gallery display",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="original_date",
            field=models.DateField(
                blank=True,
                help_text="Original date when this game was first played",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="subtitle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional subtitle displayed after game number",
                max_length=255,
            ),
        ),
    ]
