# Quotes

## 11. For each of the following quotes, is the speaker Optimus Prime from the Transformers franchise or the listed famous historical revolutionary (1 Point Each)?

"We've suffered losses, but we've not lost the war." -- Optimus

"I will never stop fighting for our freedom." -- Optimus

"Do not forget what you have learned from our past...From it's lessons, the future is forged." -- Optimus

"Even if you defeat me...others will rise to defeat your tyranny." -- Optimus

"Fate rarely calls upon as at a moment of our choosing." -- Optimus

"There's a thin line between being a hero, and being a memory." -- Optimus

"Nothing is more precious than independence and liberty." -- Ho Chi Minh

"The end may justify the means as long as there is something that justifies the end." -- Leon Trotsky

"Service to others is the rent you pay for your room here on earth." -- Muhammad Ali

"Alone we can do so little; together we can do so much." -- Helen Keller

"We cannot be sure of having something to live for unless we are willing to die for it." -- Che Guevara

"Whenever death may surprise us, let it be welcome if our battle cry has reached even one receptive ear and another hand reaches out to take up our arms." -- Che Guevara

"I have a wish. It as a fear as well - that in my end will be my beginning." -- Che Guevara

"Silence is argument carried out by other means." -- Che Guevara

"Yesterday is not ours to recover, but tomorrow is ours to win or lose." -- Lyndon B. Johnson

"He who has a why to live can bear almost any how." -- Friedrich Nietzsche

"Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment." -- Buddha

# Names

## For each of the following, what is the offical name for it?

A. Monobloc Chair 

B. Cool S

C. Emoticon

D. Punt of a wine bottle
