# Generated by Django 4.2.6 on 2023-10-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_category",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="question",
            name="question_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="pub_date",
            field=models.DateField(verbose_name="date published"),
        ),
    ]
