# Generated by Django 4.2.6 on 2023-11-02 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_question_question_category_question_question_points_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoicesSingleSlideMultipleChoiceNoAnswerBankQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=1000)),
                ("choice_answer", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=1000)),
                ("question_type", models.CharField(max_length=1000)),
                ("category", models.CharField(max_length=1000)),
                ("game_id", models.CharField(max_length=1000)),
                ("has_been_used", models.BooleanField(default=True)),
                ("question_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SingleSlideMultipleChoiceNoAnswerBankQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("points_application", models.CharField(max_length=1000)),
                ("n_options", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.questions"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.AddField(
            model_name="choicessingleslidemultiplechoicenoanswerbankquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.singleslidemultiplechoicenoanswerbankquestion",
            ),
        ),
    ]
