# Generated by Django 4.2.6 on 2023-11-02 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_choicessingleslidemultiplechoicenoanswerbankquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="points",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questions",
            name="points_application",
            field=models.CharField(default="Each", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="choicessingleslidemultiplechoicenoanswerbankquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.questions"
            ),
        ),
        migrations.DeleteModel(
            name="SingleSlideMultipleChoiceNoAnswerBankQuestion",
        ),
    ]
