# Generated by Django 4.2.6 on 2023-11-02 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_questions_points_questions_points_application_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Questions",
            new_name="Question",
        ),
    ]
